default:
  image: node:latest

build-job:
  stage: build
  script: 
    - yarn
    - yarn build

test-job:
  stage: test
  script: 
    - echo "Testing..."

deploy-job:
  stage: deploy
  script:
    - echo "Deploy"